### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by marianikitha01** [INFO526-DataViz/project-final-Data-Dynamos#1]
The following is the peer review of the project proposal by Graph Gurus. The team members that participated in this review are 
- Akrant Varshney - @AkrantVarshney 
- Hariharan Ramesh - @hari1016 
- Maria Nikitha Suresh - @marianikitha01 
- Swetha Siripurapu - @SwethaSiripurapuu 
- ...

- Describe the goal of the project.
The aim of this team’s project is to develop an engaging website that centers around visualizing information derived from the detection of asteroids in Tucson. The dataset they have chosen is titled "Asteroid Names and Discovery V4.0," and through this platform, users will have an interactive experience exploring the details of asteroid discoveries in the Tucson area.

- Describe the data used or collected.
The dataset utilized for this project is sourced from the NASA Data Portal. It contains information about 9,999 asteroids, specifically those numbered as of the 2nd February 1999 batch of Minor Planet Circulars. The dataset provides details on the asteroids, such as their names, designations, locations of finding, dates of discovery, and the identities of the people or organizations who made the discoveries.The dataset maintains its original presentation, preserving the data without alterations to account for the loss of diacritical marks due to limitations in the ASCII character set.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
The goal of this project is to create an interactive website, in order to achieve that, the team has planned to use HTML, CSS, JavaScript. And D3.js library will be used to create data-driven visualizations

- Is there anything that is unclear from the proposal?
The proposal doesn't specifically outline the team's plan for resolving the issue of unavailable datasets on NASA's website. Although it admits the difficulty, it is unclear how exactly the problem will be solved or what other sources will be used to get the necessary dataset.

- Provide constructive feedback on how the team might be able to improve their project.
To Enhance the project the team can focus on adding user-friendly filters for interactive data exploration. 

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
The timeline visualization of asteroid discoveries is a highlight and should be a focal point in the presentation, showcasing the historical progression.

- Provide constructive feedback on any issues with file and/or code organization.
The file and code organization seems well-planned. Good work

- (Optional) Any further comments or feedback?
Overall, it is a very interesting topic, and we are excited to see your visuals. Good luck!

**Comment by Swati09Das** [comment]
Hello @marianikitha01 and Team,

We went through the feedbacks and made necessary changes in our proposal.

Please find the below changes:

### Unavailability of dataset - 

We have added a back source from the NASA website and detailed the dataset in proposal.

### Constructive Feedback - 

We are considering implementing "R Shiny Application" to make it more user friendly and interactive.

Thanks for the feedback.

Regards,
Data Dynamos
