### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by bharath03-a** [INFO526-DataViz/project-final-Data-Dynamos#2]
The following is the peer review of the project proposal by Infographic Innovators. The team members that participated in this review are 

Eshaan Mathakari: @eshaanmathakari

Bharath Velamala: @bharath03-a

Thanoosha Naidu Karri: @thanooshakarri

Antonio Escalante Jr: @datalyticsintel

- Describe the goal of the project.
The goal is to create an interactive website that visualizes the asteroid discoveries in Tucson. Very clear about their overall goal is with the project. 

- Describe the data used or collected.
The dataset which is being used is sourced from NASA's data portal. From which asteroid data will be taken with columns like name, designation, discovery data, location etc,. The dataset includes 9999 entries which contains the information of asteroids numbered as of 2nd February 1999. It was also mentioned that the dataset is having ASCII character set limitation which meant that the dataset is not having diacritical marks. It is clear that they are vary of what their limitations are.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
The approach is pretty clear they wanted to visualize asteroid related data and make it accessible to users. And utilize timeline visualization, Map integration to visualize the asteroid information. And they are trying to introduce discovery details and education information for each asteroids by making it more interactive. It is interesting to see the use of D3.js library for creating the data-driven visualizations.

- Is there anything that is unclear from the proposal?
The dataset is missing from their proposal. It was not mentioned clearly on how they are planning to get the data, as they also mentioned that "**A key challenge is the availability of the data set since it has been removed from NASA website**". The goal of their project is clear but there is some deviation about what they really want to answer from the dataset. 

- Provide constructive feedback on how the team might be able to improve their project.
Maybe visualizing pattern of asteroids overtime could be good but looking at how they will manage to pinpoint the asteroid directions or so would be interesting. The proposal seemed some what deviating from what was expected, there is not much information provided on how they are going to utilize different columns in the dataset. It would have been nice if they had published their website.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
We are most interested in the visualization of the project and see how it turns out. We have never heard of Tucson being a hotspot for asteroids, so it would be interesting to see how many have landed in the area over the years. Perhaps a comparison of landings in Tucson versus the greater United States area would be interesting as well.

- Provide constructive feedback on any issues with file and/or code organization.
No issues with file and/or code organization. The plan of attack could have been organized more concisely. Folders which gets created on rendering can be ignored while pushing to git as the check for folder organization is failing due to that.

- (Optional) Any further comments or feedback?
The domain knowledge gathered for this seems interesting. Looks really interesting hope you guys find the desired dataset!

**Comment by Shakir0585** [comment]
Hey Bharath & Team,

Thank you so much for your valuable feedback.

We have made the following changes to our proposal based on the feedbacks provided:
1. Missing data set- We are in the process of obtaining the original data set from NASA, however we have also included a backup data set to proceed with our project. We have also detailed a more descriptive analysis and approach plan for this visualization based on this new data set.
2. Constructive feedback- We have now detailed a more descriptive approach for our project. We hope that this will be sufficient to address the peer review given above. Also, we will plan on comparing Tucson vs the rest of United States area and provide a probability analysis of the chances of an asteroid impact in Tucson vs the rest of USA.
3. We made some changes to the plan of attack as well, to be more organized and streamlined.

Thank you again for your feedback. We hope to impress you all with our visuals. 

Warm regards,
Data Dyanmos
