### ISSUE TITLE
Data Incoming!!

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/project-final-Data-Dynamos#4]
Hi all, 
I was emailed back about the data you were wanting from NASA. 

Here is the [link](https://sbn.psi.edu/pds/resource/discover.html)

Please note that you will be cautious because the data is raw and will likely need some exploration and cleaning. 

Good luck!
-Greg

**Comment by Shakir0585** [comment]
Thank you so much Greg!
