### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by datalyticsintel** [INFO526-DataViz/project-final-Data-Dynamos#7]
The following is the peer review of the Presentation proposal by Infographic Innovators. The team members who participated in this review are 

-Team member 1: Eshaan Mathakari: First-year graduate student in Data Science at the University of Arizona., Github: @eshaanmathakari

-  Team member 2: Bharath Velamala, First-year graduate student in Data Science at the University of Arizona., Github: @bharath03-a

-   Team member 3: Thanoosha Naidu Karri, First-year graduate student in Data Science at the University of Arizona., GitHub: @thanooshakarri

-  Team member 4: Antonio Escalante Jr, First-year graduate student in Data Science at the University of Arizona., Github: @datalyticsintel

- Content: Is the research question well designed, and is the data being used relevant to the research question?

 "What are the notable trends for meteorite landing?" is formed well for the assignment and the data used. Getting the data from NASA is also a way to ensure the data is from a trusted source. 

- Content: Did the team use appropriate visualizations, and did they interpret them accurately?

They used appropriate visualizations that illustrated what they were trying to get from the data. They did a great job explaining their plots and how they created and used the Shiny app. 

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

The project was thought out and explained; they even let us know the limitations of the project from the data, such as being unable to predict the impacts as they would have different densities from the various metals. They also shared that the Shiny app would still function appropriately by inserting different data sets, which is fantastic. We are sure that a ton of time went into planning and building the plots and apps to get them fully functional. 

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

The slides had an excellent mix of plots and text. The slides with minimal text and graphics were utilized. The text-rich slides only had relevant text, so it was good. 

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

The team did well, and they did not have any script reading. They each talked about specific slides, and the plot interruption was apparent. Each of them got to share their insights regarding the project.

**Comment by d-koudz** [comment]
Thank you :)
