### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by marianikitha01** [INFO526-DataViz/project-final-Data-Dynamos#8]
The following is the peer review of the Presentation proposal by Graph Gurus. The team members that participated in this review are 

- Swetha Siripurapuu  - @SwethaSiripurapuu 
- Hariharan Ramesh- @hari1016 
- Akrant Varshney  - @AkrantVarshney 
- Maria Nikitha Suresh  - @marianikitha01 
- ...

- Content: Is the research question well designed and is the data being used relevant to the research question?
- Yes the research question was well designed, and ofcourse the NASA dataset was relevant and the research question was well answered 

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
- The density plot was looked good and appropriate to answer the question.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
Yes the slides were organized and well presented.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the topic
- The whole team presented well and nobody rushed through the PPT, everybody got a chance to say during the presentation.
-

**Comment by d-koudz** [comment]
Thank you :)
